# Version of the docker compose syntax that we're going to be using
version: "3.9"

# Docker compose files usually consist of one or more services
services:
  # App is the name of the service that's going to run our docker file
  app:
    # Build context in the current directory
    build:
      # Dot means current directory
      context: .
      # Set build argument equal to true
      args:
        - DEV=true
    # Maps port 8000 on our local machine to port 8000 in our local container
    ports:
      - "8000:8000"
    # Volumes are a way of mapping directories from our system onto our docker container
    # We want the updates made to our code in our local project reflected in the running container in real-time
    volumes:
      - ./app:/app
    # Command that is used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
