# Three dashes signifies that it's a yaml file
---
# Name that'll appear in GitHub Actions
name: Checks

# I want these jobs to run on push
on: [push]

jobs:
  # Creates a new job ID called test-lint
  test-lint:
    # Creates the human friendly name called Test and Lint
    name: Test and Lint
    # The runner (operating system) that we'll be running our job on
    # `docker-compose` comes pre-installed in ubuntu-20.04
    runs-on: ubuntu-20.04
    # Steps are the different things that run for the job
    steps:
      # Creates the human friendly name called Login to Docker Hub
      - name: Login to Docker Hub
        # This uses a pre-made action that's provided in the GitHub actions repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Creates the human friendly name called Checkout
      - name: Checkout
        # Use GitHub's Action called checkout
        # It basically checks our code out inside our GitHub Actions job
        # By default the code is not checked out inside the job we're running
        uses: actions/checkout@v2
      # Creates the human friendly name called Test
      - name: Test
        # Runs the unit test from inside the project
        run: docker-compose run --rm app sh -c "python manage.py test"
      # Creates the human friendly name called Lint
      - name: Lint
        # Runs the linting test from inside the project
        run: docker-compose run --rm app sh -c "flake8"
